apiVersion: v1
kind: Service
metadata:
  name: wiki-app
  labels:
    app: wiki-app
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: wiki-app
    tier: frontend
  ports:
  - port: 80
    name: http
    targetPort: 3000
  - port: 443
    name: https
    targetPort: 3000