apiVersion: apps/v1
kind: Deployment
metadata:
  #Change this
  namespace: faithful-minnow
  name: wiki-app
  labels:
    app: wiki-app
    tier: frontend
spec:
  selector:
    matchLabels:
      app: wiki-app
  
  template:
    metadata:
      labels:
        app: wiki-app
        tier: frontend
    spec:
      containers:
      - name: wiki-app-frontend
        ## Container supplied by requarks - contains node.js running wiki.js
        image: requarks/wiki:2
        env:
        ## these are environment variables that we need to supply to wiki.js
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_NAME
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_PASS
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_PORT
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_TYPE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: DB_USER
        ports:
        - containerPort: 3000
